package com.gb.fineos.page.payment.benefitspaymentmanager.payments.offsetsanddeductions;

import com.gb.fineos.domain.AbstractPageRequest;
import com.gb.fineos.domain.TestCaseContext;
import com.gb.fineos.page.BasePage;
import com.gb.fineos.screencapture.ScreenCapture;
import com.relevantcodes.extentreports.LogStatus;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

public class UpdateAutoGeneratedAdjustmentAdHocDuesPage extends BasePage {

    public UpdateAutoGeneratedAdjustmentAdHocDuesPage() {
        super("UPDATE AUTO-GENERATED ADJUSTMENTS PAGE");
    }

    private void clickContinueButton(final UpdateAutoGeneratedAdjustmentAdHocDuesPageRequest pageRequest) {
        pageRequest.log(getPageName(), "Clicking on the Continue Button");
        try {
            getDriver().findElements(By.xpath("//input[contains(@id,'continue')]"))
                .stream()
                .findFirst()
                .ifPresent(WebElement::click);
        } catch (Exception e) {
            ScreenCapture.logScreenshot(getPageName(), LogStatus.ERROR);
            pageRequest.log(getPageName(), "There was an issue when attempting to click the continue button");
            throw e;
        }
    }

    public void handleAutoGeneratedAdjustmentPage(final UpdateAutoGeneratedAdjustmentAdHocDuesPage.UpdateAutoGeneratedAdjustmentAdHocDuesPageRequest pageRequest) {
        getDriver().findElements(By.xpath("//span[text()='Update Auto-Generated Adjustments']"))
            .stream()
            .filter(WebElement::isDisplayed)
            .findFirst()
            .ifPresent(webElement -> {
                ScreenCapture.logScreenshot(getPageName(), LogStatus.INFO);
                clickContinueButton(pageRequest);
            });
    }


    public static class UpdateAutoGeneratedAdjustmentAdHocDuesPageRequest extends AbstractPageRequest {

        public UpdateAutoGeneratedAdjustmentAdHocDuesPageRequest(final TestCaseContext context) {
            super(context);
        }

    }
}
